### ISSUE TITLE
TypeError: contentCatalog.exportToModel is not a function

### ISSUE THREAD

**Issue by gaudigde** [Mogztter/antora-site-generator-lunr#64] opened 2020-08-04 18:27 UTC
I get an error when using the antora-site-generator-lunr v0.5.0. Without the option `--generator antora-site-generator-lunr` Antora works fine. I followed the installation instructions and I’m using Antora 2.3.3 with the default UI. Before upgrading from Antora 2.2 and antora-site-generator-lunr v0.3.0 everything was working as expected.

**Update**: It seems that the version 0.5.0 is the problem. Antora 2.3.3 with antora-site-generator-lunr 0.3.0 is working.

Here’s the stacktrace:
```
$ CI=1 DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr npx antora playbook-dev.yml --generator antora-site-generator-lunr --stacktrace
TypeError: contentCatalog.exportToModel is not a function
    at buildBaseUiModel (/builds/abc/def/ghi/antora.playbook/node_modules/@antora/page-composer/lib/build-ui-model.js:10:46)
    at createPageComposer (/builds/abc/def/ghi/antora.playbook/node_modules/@antora/page-composer/lib/create-page-composer.js:45:37)
    at generateSite (/builds/abc/def/ghi/antora.playbook/node_modules/antora-site-generator-lunr/lib/generate-site.js:25:23)
    at async run (/builds/abc/def/ghi/antora.playbook/node_modules/@antora/cli/lib/cli.js:17:21)
```

**Comment by Mogztter** [comment] 2020-08-12 12:33
`exportToModel` was added in Antora 2.3.0: https://gitlab.com/antora/antora/-/commit/14dd15387423e2ac86e68af0fb52e7faddabd133

We have integration tests against master (0.5.0) and Antora 2.3.3.
Did you follow this procedure to upgrade: https://github.com/Mogztter/antora-site-generator-lunr#upgrading?
Unless I'm missing something, I think this is an installation issue, please make sure that you are using Antora 2.3.3 with version 0.5.0.

**Comment by Mogztter** [comment] 2020-11-14 18:03
@gaudigde friendly ping! can you please confirm (or not) that you solved this issue?

**Comment by Mogztter** [comment] 2020-11-24 09:57
Closing, feel free to reopen if the issue is not solved.

**Closed by Mogztter** 2020-11-24 09:57 UTC
